name: ${project.name}
main: net.enelson.sopitemscreator.SopItemsCreator
version: ${project.version}
authors: [E_NeLsOn]
depend: [NBTAPI]
api-version: 1.16
commands:
  sopitemscreator:
permissions:
  sopitemscreator.admin:
    default: op
